Map<String, String> defaultLanguageTranslatedValues = {
  "onBoardingFirstTitle": "Artistic Expressions",
  "onBoardingFirstDescription":
      "Unleash your creativity through diverse artworks at Artistic Expressions.",
  "onBoardingSecondTitle": "Mystic Showdown",
  "onBoardingSecondDescription":
      "Unleash your magical talents and compete in a mystical showdown of spells and illusions!",
  "onBoardingThirdTitle": "Sonic Showdown",
  "onBoardingThirdDescription":
      "Let your voice shine in a Sonic Showdown where singing talents from around  the world gather to compete.",
  "onBoardingFourthTitle": "The Art of Cooking",
  "onBoardingFourthDescription":
      "Step into the culinary arena and showcase your cooking prowess in a sizzling competition!",
  "skip": "Skip",
  "signIn": "Sign In",
  "signUp": "Sign Up",
  "login": "Login",
  "pleaseLoginWithCurrentDetails": "Please login with current credentials",
  "email": "Email",
  "password": "Password",
  "enterYourEmail": "Enter your email",
  "enterYourPassword": "Enter your password",
  "forgotPassword": "Forgot Password?",
  "iAgreeToThe": "I agree to the",
  "and": "and",
  "termsAndConditions": "Terms & Conditions",
  "privacyPolicy": "Privacy Policy",
  "submit": "Submit",
  "createYourAccount": "Create your account",
  "step": "Step",
  "contact": "Contact",
  "confirmPassword": "Confirm Password",
  "country": "Country",
  "profileImage": "Profile Image",
  "agreeThatUserIs13YearOlder": "I agree that i am 13 years old or older",
  "enterYourFullName": "Enter your full name",
  "fullName": "Full Name",
  "enterConfirmPassword": "Enter confirm paassword",
  "next": "Next",
  "back": "Back",
  "uploadProfileImage": "Upload your profile image",
  "noWorriesSendYouInstructionsKey":
      "No worries, we'll send you reset instructions",
  "resetPassword": "Reset paassword",
  "checkYourEmail": "Check your email",
  "weSendPasswordResetLink": "We have sent password reset link to",
  "openEmailApp": "Open email app",
  "didnotReceiveTheEmail": "Did't receive the email?",
  "clickToResend": "Click to resend",
  "home": "Home",
  "leaderboard": "Leaderboard",
  "talent": "Talent",
  "voting": "Voting",
  "competition": "Competition",
  "welcomeBack": "Welcome back,",
  "upcomingCompetitions": "Upcoming Competitions",
  "more": "More",
  "latestUpdates": "Latest Updates",
  "popularPerformance": "Popular Performance",
  "closeCompetition": "Close competition",
  "name": "Name",
  "rank": "Rank",
  "profile": "Profile",
  "status": "Status",
  "votes": "Votes",
  "voteNow": "Vote Now",
  "upcoming": "Upcoming",
  "live": "Live",
  "past": "Past",
  "setFilters": "Set Filters",
  "search": "Search",
  "region": "Region",
  "subCategory": "Sub Category",
  "selectRegionName": "Select region name",
  "selectSubcategory": "Select Subcategory",
  "applyFilters": "Apply",
  "clear": "Clear",
  "share": "Share",
  "about": "About",
  "comment": "Comment",
  "vote": "Vote",
  "images": "Images",
  "videos": "Videos",
  "generalDetails": "General details",
  "votingDetails": "Voting details",
  "startsOn": "Starts on",
  "endsOn": "Ends on",
  "liveFor": "Live for",
  "totalVotes": "Total votes",
  "yearsOfExperience": "Years of experience",
  "languageSpoken": "Language spoken",
  "joinDate": "Join date",
  "contactUs": "Contact us",
  "subject": "Subject",
  "message": "Message",
  "enterYourSubject": "Enter your subject",
  "enterMessage": "Enter message",
  "viewComments": "View comments",
  "addComment": "Add comment",
  "enterYourText": "Enter your text",
  "competitionDetails": "Competition details",
  "totalDaysOfCompetitionRound": "Total days of Competition Round",
  "competitionRound": "Competition Round",
  "competitionType": "Competition Type",
  "competitionCategory": "Competition Category",
  "registration": "Registration",
  "entryFees": "Entry fees",
  "groupName": "Group name",
  "enterYourGroupName": "Enter your group name",
  "age": "Age ( minimum & maximum age )",
  "enterYourGroupAge": "Enter your group age (Ex. 15-50)",
  "groupMember": "Group member",
  "enterYourGroupMember": "Enter your group member",
  "groupExperience": "Group experience",
  "enterYourGroupExperience": "Enter your group experience",
  "image": "Image",
  "uploadImage": "Upload image",
  "addVideoUrl": "Add video url",
  "enterYourVideoUrl": "Enter your video url",
  "addDescription": "Add description",
  "enterYourDescription": "Enter your description",
  "additionalInformation": "Additional information",
  "language": "Language",
  "socialHandles": "Social handles",
  "successStories": "Success stories",
  "changePassword": "Change password",
  "aboutUs": "About us",
  "logout": "Logout",
  "deleteAccount": "Delete account",
  "editProfile": "Edit profile",
  "languageSpoke": "Language spoke",
  "hobbies": "Hobbies",
  "enterYourHobbies": "Enter your hobbies",
  "enterYearsOfExperience": "Enter years of experience",
  "changeLanguage": "Change language",
  "defaultErrorMessage": "Something went wrong.Please try again later!",
  "noInternet": "No Internet",
  "participatedCompetitions": "Participated competitions",
  "video": "Video",
  "instagramProfile": "Instagram profile",
  "tiktokProfile": "Tik Tok profile",
  "facebookProfile": "Facebook profile",
  "youtubeProfile": "Youtube profile",
  "enterInstagramProfileLink": "Enter your instagram profile link",
  "enterYourTiktokProfileLink": "Enter your tiktok profile link",
  "enterYourFacebookProfileLink": "Enter your facebook profile link",
  "enterYourYoutubeProfileLink": "Enter your youtube profile link",
  "uploadYourSuccessStory": "Upload your success story",
  "addYourSuccessStory": "Add your success story",
  "currentPassword": "Current password",
  "enterYourCurrentPassword": "Enter your current password",
  "newPassword": "New password",
  "enterYourNewPassword": "Enter your new password",
  "areYouSureYouWantToLogout": "Are you sure you want to logout your account?",
  "yesLogout": "Yes, Logout",
  "stayLoggedIn": "Stay logged in",
  "areYouSureYouWantToDeleteAccount":
      "Are you sure you want to delete your account?",
  "yesDelete": "Yes, Delete",
  "keepAccount": "Keep account",
  "notifications": "Notifications",
  "pleaseAcceptTermsAndConditionAndPrivacyPolicy":
      "Please accept Terms & condition and Privacy policy",
  "pleaseEnterEmail": "Please enter email",
  "pleaseEnterPassword": "Please enter password",
  "hello": "Hello",
  "guest": "Guest",
  "retry": "Retry",
  "loginSignUp": "Login/Sign up",
  "verify": "Verify",
  "pleaseEnterContact": "Please enter contact",
  "OTP": "OTP",
  "enterOtpHere": "Enter otp here",
  "resendCode": "Resend code",
  "changeContact": "Change contact",
  "verifyContact": "Verify contact",
  "weHaveSentOtpTo": "We have sent otp to",
  "youWillGetAnOtpOn": "You will get an otp on",
  "incorrectOTP": "Incorrect otp",
  "setNewPassword": "Set new password",
  "passwordUpdatedSuccessfully": "Password updated successfully",
  "pleaseEnterFullName": "Please enter full name",
  "profileUpdatedSuccessfully": "Profile updated successfully",
  "pleaseGiveStoragePermission": "Please give storage permission",
  "updatedSocialMediaHandlesSuccessfully":
      "Updated social media handles successfully",
  "pleaseEnterCurrentPassword": "Please enter current password",
  "pleaseEnterConfirmPassword": "Please enter confirmp password",
  "pleaseEnterNewPassword": "Please enter new password",
  "minimumPasswordLengthis8": "Minimum password length is 8",
  "newPasswordAndConfirmPasswordMustBeSame":
      "New password and confirm password must be same",
  "passwordChangedSuccuessfully": "Password changed succuessfully",
  "passwordAndConfirmPasswordMustBeSame":
      "Password and confirm password must be same",
  "pleaseAcceptYouAre13YearsOldOrOlder":
      "Please accept you are 13 years old or older",
  "pleaseSelectProfileImage": "Please select profile image",
  "userNotFound": "User not found",
  "weHaveSentVerificationLinkOn": "We have sent verification link on",
  "emailAlreadyExist": "Email already exist",
  "noPastCompetitions": "No past competitions",
  "noLiveCompetitions": "No live competitions",
  "noUpcomingCompetitions": "No upcoming competitions",
  "all": "All",
  "category": "Category",
  "round": "Round",
  "voteParticipant": "Vote participant",
  "areYouSureToVote": "Are you sure to vote this participant?",
  "voted": "Voted",
  "leaderboardEmpty":
      "Looks like leaderboard is empty. Go and vote your favorite contestant",
  "commentAddedSuccessfully": "Comment added successfully",
  "pleaseEnterSubject": "Please enter subject",
  "pleaseEnterMessage": "Please enter message",
  "registrationFrom": "Registration from",
  "registrationEnds": "Registration ends",
  "goBack": "Go back",
  "verifyingTransaction": "Verifying transaction",
  "hangOnVerifyingTransaction": "Hang on, Verifying the transaction.",
  "willNotifyYouAboutPaymentTransaction":
      "Don't worry, your money is in safe hands. We will notify you once your transaction get verified then you can continue the registration process.  You can close this screen or app safely",
  "pleaseEnterGroupName": "Please enter group name",
  "pleaseEnterAge": "Please enter age",
  "pleaseEnterGroupExperience": "Please enter group experience",
  "pleaseEnterGroupMember": "Please enter group member",
  "pleaseEnterDescription": "Please enter description",
  "pleaseSelectImages": "Please select all images",
  "pleaseEnterVideoUrls": "Please enter all video urls",
  "currentRound": "Current round",
  "roundWillStartsOn": "Round will starts on",
  "paymentFailedTryAgainLater": "Payment failed, Please try again later",
  "youCanCloseTheAppOrScreen": "You can close this screen or app safely",
  "willNotifyYou":
      "We are verifying the transaction. Don't worry, your money is in safe hands. We will notify you once your transaction get verified",
  "wait": "Wait",
  "continuePayment": "Continue payment",
  "pendingPaymentTransactionWarning":
      "We have detected a recent pending transaction initiated by you. We recommend you to wait for 30 minutes before initiating a new transaction.",
  "competitionName": "Competition name",
  "roundNotStartedYet": "Round not started yet",
  "imagesAndVideoAddedSuccessfully": "Images and video added successfully",
  "noParticipants": "No participants",
  "couldNotMakeItToThisRound": "Alas you couldn't make it to this round",
  "groupDetails": "Group details",
  "groupAge": "Group age",
  "selectCountryName": "Select country name",
  "selectLanguage": "Select language",
  "searchCompetitionsAndParticipants": "Search competitions and participants",
  "categories": "Categories",
  "accountDeletedSuccessfully": "Account deleted successfully",
  "winner": "Winner",
  "winningPrize": "Winning Prize",
  "youAreTheWinnerOfThisCompetition":
      "Congratulations, you are the winner of this competition",
  "subCategories": "Sub categories",
  "competitions": "Competitions",
  "completed": "Completed",
  "noCompetitions": "No competitions",
  "successStory": "Success story",
  "newPerformances": "New Performances",
  "liveCompetitions": "Live Competitions",
  "inTheSpotLight": "In The Spotlight",
  "quizWinner": "Quiz winners",
  "ourSponsors": "Our sponsors",
  "quiz": "Quiz",
  "chooseVideo": "Choose Video",
  "thumbnailImage": "Thumbnail Image",
  "uploadVideo": "Upload video",
  "shortVideoDurationNote": "Duration of the video must be",
  "videoSizeLimitNote": "Size of the video must be less than",
  "pleaseSelectThumbnailImage": "Please select thumbnail image",
  "pleaseUploadVideo": "Please upload video",
  "pleaseUploadVideoOrAddVideoUrl": "Please upload video or video url",
  "youCanUploadVideoOrAddVideoUrl": "You can either upload video or add url",
  "shortVideo": "Short video",
  "pleaseEnterVideoDescription": "Please enter video description",
  "videoDescription": "Video description",
  "aboutYou": "About you",
  "yourRegistrationHasBeenSuccessful": "Your registration has been successful",
  "totalRound": "Total Round",
  "qualifiedUntil": "Qualified until",
  "participants": "Participants",
  "competitionRounds": "Competition rounds",
  "competitionEndsOn": "Competition ends on",
  "registered": "Registered",
  "continue": "Continue",
  "register": "Register",
  "aboutGroup": "About group",
  "seats": "Seats",
  "openRegistration": "Open registration",
  "prizeDetails": "Prize details",
  "sponsorBy": "Sponsor by",
  "faqs": "FAQs",
  "totalParticipants": "Total participants",
  "number": "No.",
  "details": "Details",
  "performances": "Performances",
  "winners": "Winners",
  "roundEndsOn": "Round ends on",
  "users": "Users",
  "searchParticipants": "Search participants",
  "votingClosesOn": "Voting closes on",
  "popularShorts": "Popular shorts",
  "unableToFindUsersOrCompetitions": "Unable to find users or competitions",
  "participated": "Participated",
  "runnerUp": "Runner up",
  "won": "Won",
  "viewLive": "View live",
  "userInfo": "User info",
  "competitionInfo": "Competition info",
  "votingWillClosedIn": "Voting will closed in",
  "noComments": "No comments",
  "forum": "Forum",
  "announcements": "Announcements",
  "discussions": "Discussions",
  "addaAAnswer": "Add a answer",
  "addAReply": "Add a reply",
  "viewMoreReply": "View more reply",
  "viewReplies": "View replies",
  "askYourQuestion": "Ask your question",
  "post": "Post",
  "writeYourQuestionHere": "Write your question here",
  "participatedIn": "Participated in",
  "howToPlay": "How to play",
  "quizCompetition": "Quiz competition",
  "quizEndsOn": "Quiz ends on",
  "players": "Players",
  "playNow": "Play now",
  "played": "Played",
  "score": "Score",
  "playMore": "Play more",
  "checkLeaderboard": "Check leaderboard",
  "noAnnouncements": "No announcements",
  "searchTopics": "Search topics",
  "noTopicsFound": "No topics found ):",
  "questionPostedSuccessfully": "Question posted successfully",
  "searchAnyQuestions": "Search any questions",
  "questionsNotFound": "Questions not found",
  "searchAnswer": "Search answer",
  "couldNotFindSearchedAnswer": "Couldn't find searched answer",
  "startTimerAndShowOptions": "Start timer and show options",
  "submittingQuizResult":
      "Do not close the app or screen, we are submitting the quiz result",
  "areYouSureToQuizTheQuiz": "Are you sure to quiz the quiz?",
  "yes": "Yes",
  "no": "No"
};
