///
///[PLEASE DO NOT MODIFIED THIS MODULE IDS]
///
library;

const int studentManagementModuleId = 1;
const int academicsManagementModuleId = 2;
const int sliderManagementModuleId = 3;
const int teacherManagementModuleId = 4;
const int sessionYearManagementId = 5;
const int holidayManagementModuleId = 6;
const int timetableManagementModuleId = 7;
const int attendanceManagementModuleId = 8;
const int examManagementModuleId = 9;
const int lessonManagementModuleId = 10;
const int assignmentManagementModuleId = 11;
const int announcementManagementModuleId = 12;
const int staffManagementModuleId = 13;
const int expenseManagementModuleId = 14;
const int staffLeaveManagementModuleId = 15;
const int feesManagementModuleId = 16;
const int galleryManagementModuleId = 17;
const int chatModuleId = 20;
const int defaultModuleId = -1;
const String moduleIdJoiner = "#";

///[Please do not edit this]
///
const String approveLeavePermissionKey = "approve-leave";
const String viewTeachersPermissionKey = "teacher-list";
const String viewStudentsPermissionKey = "student-list";
const String viewStaffsPermissionKey = "staff-list";
const String viewTimetablePermissionKey = "timetable-list";
const String viewStudentAttendancePermissionKey = "attendance-list";
const String viewClassesPermissionKey = "class-list";
const String viewExamsPermissionKey = "exam-list";
const String viewExamTimetablePermissionKey = "exam-timetable-list";
const String viewExamResultPermissionKey = "exam-result";
const String viewSessionYearsPermissionKey = "session-year-list";
const String viewSemestersPermissionKey = "semester-list";

//
const String viewNotificationPermissionKey = "notification-list";
const String createNotificationPermissionKey = "notification-create";
const String editNotificationPermissionKey = "notification-edit";
const String deleteNotificationPermissionKey = "notification-delete";

//

const String viewAnnouncementPermissionKey = "announcement-list";
const String createAnnouncementPermissionKey = "announcement-create";
const String editAnnouncementPermissionKey = "announcement-edit";
const String deleteAnnouncementPermissionKey = "announcement-delete";

//
const String viewFeesPaidPermissionKey = "fees-paid";
const String viewPayrollListPermissionKey = "payroll-list";
const String editPayrollEditPermissionKey = "payroll-edit";
const String createPayRollPermissionKey = "payroll-create";

//"teacher-list",
/*
0=>"role-list"
1=>"role-create"
2=>"role-edit"
3=>"role-delete"
4=>"medium-list"
5=>"medium-create"
6=>"medium-edit"
7=>"medium-delete"
8=>"section-list"
9=>"section-create"
10=>"section-edit"
11=>"section-delete"
12=>"class-list"
13=>"class-create"
14=>"class-edit"
15=>"class-delete"
16=>"class-section-list"
17=>"class-section-create"
18=>"class-section-edit"
19=>"class-section-delete"
20=>"subject-list"
21=>"subject-create"
22=>"subject-edit"
23=>"subject-delete"
24=>"teacher-list"
25=>"teacher-create"
26=>"teacher-edit"
27=>"teacher-delete"
28=>"guardian-list"
29=>"guardian-create"
30=>"guardian-edit"
31=>"guardian-delete"
32=>"session-year-list"
33=>"session-year-create"
34=>"session-year-edit"
35=>"session-year-delete"
36=>"student-list"
37=>"student-create"
38=>"student-edit"
39=>"student-delete"
40=>"timetable-list"
41=>"timetable-create"
42=>"timetable-edit"
43=>"timetable-delete"
44=>"attendance-list"
45=>"attendance-create"
46=>"attendance-edit"
47=>"attendance-delete"
48=>"holiday-list"
49=>"holiday-create"
50=>"holiday-edit"
51=>"holiday-delete"
52=>"announcement-list"
53=>"announcement-create"
54=>"announcement-edit"
55=>"announcement-delete"
56=>"slider-list"
57=>"slider-create"
58=>"slider-edit"
59=>"slider-delete"
60=>"promote-student-list"
61=>"promote-student-create"
62=>"promote-student-edit"
63=>"promote-student-delete"
64=>"language-list"
65=>"language-create"
66=>"language-edit"
67=>"language-delete"
68=>"lesson-list"
69=>"lesson-create"
70=>"lesson-edit"
71=>"lesson-delete"
72=>"topic-list"
73=>"topic-create"
74=>"topic-edit"
75=>"topic-delete"
76=>"schools-list"
77=>"schools-create"
78=>"schools-edit"
79=>"schools-delete"
80=>"form-fields-list"
81=>"form-fields-create"
82=>"form-fields-edit"
83=>"form-fields-delete"
84=>"grade-list"
85=>"grade-create"
86=>"grade-edit"
87=>"grade-delete"
88=>"package-list"
89=>"package-create"
90=>"package-edit"
91=>"package-delete"
92=>"addons-list"
93=>"addons-create"
94=>"addons-edit"
95=>"addons-delete"
96=>"guidance-list"
97=>"guidance-create"
98=>"guidance-edit"
99=>"guidance-delete"
100=>"assignment-list"
101=>"assignment-create"
102=>"assignment-edit"
103=>"assignment-delete"
104=>"assignment-submission"
105=>"exam-list"
106=>"exam-create"
107=>"exam-edit"
108=>"exam-delete"
109=>"exam-timetable-list"
110=>"exam-timetable-create"
111=>"exam-timetable-edit"
112=>"exam-timetable-delete"
113=>"exam-upload-marks"
114=>"exam-result"
115=>"system-setting-manage"
116=>"fcm-setting-create"
117=>"email-setting-create"
118=>"privacy-policy"
119=>"contact-us"
120=>"about-us"
121=>"terms-condition"
122=>"class-teacher"
123=>"student-reset-password"
124=>"reset-password-list"
125=>"student-change-password"
126=>"update-admin-profile"
127=>"fees-classes"
128=>"fees-paid"
129=>"fees-config"
130=>"school-setting-manage"
131=>"app-settings"
132=>"subscription-view"
133=>"online-exam-list"
134=>"online-exam-create"
135=>"online-exam-edit"
136=>"online-exam-delete"
137=>"online-exam-questions-list"
138=>"online-exam-questions-create"
139=>"online-exam-questions-edit"
140=>"online-exam-questions-delete"
141=>"online-exam-result-list"
142=>"fees-type-list"
143=>"fees-type-create"
144=>"fees-type-edit"
145=>"fees-type-delete"
146=>"fees-class-list"
147=>"fees-class-create"
148=>"fees-class-edit"
149=>"fees-class-delete"
150=>"role-list"
151=>"role-create"
152=>"role-edit"
153=>"role-delete"
154=>"staff-list"
155=>"staff-create"
156=>"staff-edit"
157=>"staff-delete"
158=>"expense-category-list"
159=>"expense-category-create"
160=>"expense-category-edit"
161=>"expense-category-delete"
162=>"expense-list"
163=>"expense-create"
164=>"expense-edit"
165=>"expense-delete"
166=>"semester-list"
167=>"semester-create"
168=>"semester-edit"
169=>"semester-delete"
170=>"payroll-list"
171=>"payroll-create"
172=>"payroll-edit"
173=>"payroll-delete"
174=>"stream-list"
175=>"stream-create"
176=>"stream-edit"
177=>"stream-delete"
178=>"shift-list"
179=>"shift-create"
180=>"shift-edit"
181=>"shift-delete"
182=>"leave-list"
183=>"leave-create"
184=>"leave-edit"
185=>"leave-delete"
186=>"approve-leave"
187=>"faqs-list"
188=>"faqs-create"
189=>"faqs-edit"
190=>"faqs-delete"
191=>"fcm-setting-manage"
192=>"fees-list"
193=>"fees-create"
194=>"fees-edit"
195=>"fees-delete"
196=>"transfer-student-list"
197=>"transfer-student-create"
198=>"transfer-student-edit"
199=>"transfer-student-delete"
200=>"gallery-list"
201=>"gallery-create"
202=>"gallery-edit"
203=>"gallery-delete"
204=>"notification-list"
205=>"notification-create"
206=>"notification-edit"
207=>"notification-delete"
208=>"payment-settings"
209=>"subscription-settings"
210=>"subscription-change-bills"
211=>"school-terms-condition"
212=>"student-id-card-settings"
213=>"subscription-bill-payment"
214=>"web-settings"

 */
